#! /bin/bash
#
# Build a clean INN
#
set -e
. ./config
cd $DIR
echo autogen ...
./autogen
echo configure ...
./configure --prefix=$PREFIX --with-perl --with-python --with-openssl \
            --with-sasl --with-news-user=${USER} --with-news-group=${USER} \
            --enable-largefiles --with-innd-port=1119 --with-bdb --with-zlib \
            > configure.log 2>&1
cd -
echo make bootstrap ...
make -C $DIR bootstrap > bootstrap.log 2>&1
echo make clean ...
make -C $DIR clean > clean.log 2>&1
echo make ...
make -C $DIR -j4 > build.log 2>&1
echo make check ...
make -C $DIR check > check.log 2>&1
