#! /bin/bash
#
# Copyright 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Build a clean INN
#
set -e
. ${INNTEST_CONFIG:-./config}
SELF=$(pwd)
if ! [ -d $DIR ] && [ -f $DIR.tar.gz ]; then
    echo unpack ...
    tar xf $DIR.tar.gz 
fi
cd $DIR
echo autogen ...
./autogen
echo configure ...
set -- --prefix=$PREFIX --with-perl --with-python --with-openssl \
            --with-sasl --with-news-user=${USER} --with-news-group=${USER} \
            --enable-largefiles --with-innd-port=1119 --with-bdb --with-zlib
./configure "$@" > ${SELF}/configure.log 2>&1 || { cat ${SELF}/configure.log; cat config.log; exit 1; }
cd ${SELF}
echo make bootstrap ...
make -C $DIR bootstrap > bootstrap.log 2>&1 || { cat bootstrap.log; exit 1; }
echo make clean ...
make -C $DIR clean > clean.log 2>&1 || { cat clean.log; exit 1; }
echo make ...
make -C $DIR -j$(nproc) > build.log 2>&1 || { cat build.log; exit 1; }
echo make check ...
make -C $DIR check > check.log 2>&1 || { cat check.log; exit 1; }
echo build complete
