#! /bin/bash
#
# Install a clean INN
#
set -e
. config
SELF=$(pwd)
cd $DIR
if [ -e $PREFIX/etc/inn.conf ]; then
    echo shutdown ...
    ${REALLY} su - ${USER} -c "${PREFIX}/bin/ctlinnd shutdown make-test-inn" > shutdown.log 2>&1 || true
    sleep 3                         # just in case...
fi
${REALLY} rm -rf $PREFIX/etc/*
${REALLY} rm -rf $PREFIX/bin/*.real
echo install ...
${REALLY} make -C $DIR install > install.log 2>&1
if ${VALGRIND:-false}; then
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/innd
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/innfeed
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/nnrpd
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/innxmit
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/inews
    ${REALLY} $SELF/valgrindize --log $PREFIX/log $PREFIX/bin/ctlinnd
fi
