#! /bin/bash
#
# Copyright 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
. ${INNTEST_CONFIG:-./config}

echo
echo ==== Main test run ====
echo

./install
./configure

echo extra configuration...

${REALLY} sh -c "cat >> $PREFIX/etc/innfeed.conf" <<EOF
peer ${DOMAIN} {
  ip-name: localhost
  port-number: ${LOCALPORT}
}

initial-sleep: 0
initial-reconnect-time:         1
max-reconnect-time:             1
EOF

${REALLY} sh -c "cat >> $PREFIX/etc/newsfeeds" <<EOF
innfeed!:!*:Tc,Wnm*:$PREFIX/bin/innfeed
${DOMAIN}:${GROUP}:Tm:innfeed!
EOF

./start
./test-nntpbits innfeed
./shutdown
