#! /bin/sh
#
# Test using nntpbits
#
set -e
. ./config

echo "=== $0 $1 ==="

./tests.py ${DEBUG} \
           -s "${SERVER}" -p "${PORT}" \
           -g "${GROUP}" -D "${DOMAIN}" -l "${LOCALPORT}" \
           -T "./trigger"
