#! /bin/bash
#
# Copyright Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
. ${INNTEST_CONFIG:-./config}

case "$#" in
1 )
    ;;
* )
    cat >&2 <<EOF
ERROR: usage: test-docker TARBALL

Example of tar creation:
  git archive --prefix inn/ HEAD | gzip -9c > inn.tar.gz
EOF

    exit 1
esac

[ -f sources.buster ] || touch sources.buster

echo docker build ...
docker build -t ${INNTEST_CONTAINER:-inntest} .

echo docker run ...
docker run \
    --mount type=bind,source="$1",target=/work/inn.tar.gz \
    --hostname ${PATHHOST} \
    inntest:latest /work/test-docker-run
