#! /bin/sh
#
# Test article injection
#
set -e
. ./config

echo === $0 ===

echo Injecting article locally
LOCAL_CODE=$(dd if=/dev/urandom count=1 bs=24 status=none | base64)
${REALLY} su - tnews -c "$PREFIX/bin/inews -h -p 1119" <<EOF
Newsgroups: greenend.test
Subject: [do-test-inn] local injection

$LOCAL_CODE
EOF

echo Checking article present in spool
if ! grep -Fq $LOCAL_CODE $PREFIX/spool/articles/greenend/test/*; then
    echo "Local injection failed ($LOCAL_CODE)"
    exit 1
fi

case "$1" in
    nntpsend )
        ${REALLY} su - tnews -c "$PREFIX/bin/ctlinnd -s flush ''"
        sleep 2
        ${REALLY} su - tnews -c "$PREFIX/bin/nntpsend"
        ;;
esac

sleep 2
echo Checking article present in remote spool
if ! grep -Fq $LOCAL_CODE /var/spool/news/articles/greenend/test/*; then
    echo "Outbound peering failed ($LOCAL_CODE)"
    exit 1
fi

echo OK
