#! /bin/bash
set -e
. ./config

./build

echo
echo ==== Main test run ====
echo

./install
./configure core.diff innfeed.diff
./test-injection innfeed
./test-receipt

echo
echo ==== nntpsend tests ====
echo

./install
./configure core.diff nntpsend.diff
./test-injection nntpsend
./test-receipt
