#! /bin/bash
#
# Copyright 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
. ${INNTEST_CONFIG:-./config}

echo
echo ==== Alternative config test run ====
echo

./install
./configure

echo extra configuration...

${REALLY} sh -c "sed 's/1536000/1024/' < $PREFIX/etc/buffindexed.conf > $PREFIX/etc/buffindex.conf.new"
${REALLY} mv $PREFIX/etc/buffindex.conf.new $PREFIX/etc/buffindexed.conf

${REALLY} su - ${USER} -c 'dd if=/dev/zero of=/usr/local/news/spool/overview/OV1 bs=1024 count=1024 status=none'
${REALLY} su - ${USER} -c 'dd if=/dev/zero of=/usr/local/news/spool/overview/OV2 bs=1024 count=1024 status=none'

${REALLY} sh -c "sed 's/ovmethod:.*/ovmethod: buffindexed/' < $PREFIX/etc/inn.conf > $PREFIX/etc/inn.conf.new"
${REALLY} mv $PREFIX/etc/inn.conf.new $PREFIX/etc/inn.conf

${REALLY} sh -c "cat >> $PREFIX/etc/newsfeeds" <<EOF
${DOMAIN}:${GROUP}:Tf,Wnm:
EOF

${REALLY} sh -c "cat >> $PREFIX/etc/nntpsend.ctl" <<EOF
${DOMAIN}:localhost::
EOF
# (port number is -P argument to nntpsend, see trigger script)

./start
./test-nntpbits nntpsend
./shutdown
