#! /bin/bash
set -e
SELF="$(dirname "$0")"
logdir=$(pwd)
while [ $# -gt 0 ]; do
    case "$1" in
        -- )
            shift
            break
            ;;
        --log )
            shift
            logdir=$1
            shift
            ;;
        -* )
            echo "ERROR: unrecognized option '$1'" >&2
            exit 1
            ;;
        * )
            break
            ;;
    esac
done
for path; do
    if [ -e $path.real ]; then
        echo "ERROR: $path: already valgrindized" >&2
        exit 1
    fi
done
for path; do
    mv "$path" "$path.real"
    echo "#! /bin/sh" > "$path"
    echo "set -" >> "$path"
    echo "exec valgrind -q --suppressions=$SELF/valgrind-python.supp --num-callers=64 --leak-check=yes --log-file=$logdir/\$(date +%F-%H%M%S).$(basename $path).\$\$.log $path.real \"\$@\"" >> "$path"
    chmod +x "$path"
done
