#! /bin/bash
#
# Copyright 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
SELF="$(dirname "$0")"
logdir=$(pwd)
while [ $# -gt 0 ]; do
    case "$1" in
        -- )
            shift
            break
            ;;
        --log )
            shift
            logdir=$1
            shift
            ;;
        -* )
            echo "ERROR: unrecognized option '$1'" >&2
            exit 1
            ;;
        * )
            break
            ;;
    esac
done
for path; do
    if [ -e $path.real ]; then
        echo "ERROR: $path: already valgrindized" >&2
        exit 1
    fi
done
for path; do
    mv "$path" "$path.real"
    echo "#! /bin/sh" > "$path"
    echo "set -" >> "$path"
    echo "exec valgrind -q --suppressions=$SELF/valgrind-python.supp --num-callers=64 --leak-check=yes --log-file=$logdir/\$(date +%F-%H%M%S).$(basename $path).\$\$.log $path.real \"\$@\"" >> "$path"
    chmod +x "$path"
done
