#! /bin/bash
#
# Copyright 2015 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
SELF="$(realpath $(dirname "$0"))"
logdir=$(pwd)
force=false
act=true
while [ $# -gt 0 ]; do
    case "$1" in
        -- )
            shift
            break
            ;;
        -l | --log )
            shift
            logdir=$1
            shift
            ;;
        -f | --force )
            shift
            force=true
            ;;
        -n | --no-act )
            shift
            act=false
            ;;
        -* )
            echo "ERROR: unrecognized option '$1'" >&2
            exit 1
            ;;
        * )
            break
            ;;
    esac
done
for path; do
    case "$path" in
        *.real )
            continue
            ;;
    esac
    if ! [ -f $path ]; then
        continue
    fi
    if [ -e $path.real ]; then
        echo "WARNING: $path: already valgrindized" >&2
        continue
    fi
    if ! file $path | grep -q ELF.*executable; then
        if $force; then
            echo WARNING: valgrindizing $path even thought not ELF >&2
        else
            continue
        fi
    fi
    if $act; then
        mv "$path" "$path.real"
        realpath=$(realpath "$path.real")
        echo "#! /bin/sh" > "$path"
        echo "set -" >> "$path"
        echo "exec valgrind -q --suppressions=$SELF/valgrind-python.supp --num-callers=64 --leak-check=yes --log-file=$logdir/\$(date +%F-%H%M%S).$(basename $path).\$\$.log $realpath \"\$@\"" >> "$path"
        chmod +x "$path"
    else
        echo $path
    fi
done
